In [1]:
import numpy as np

In [96]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0],[0],[0],[1]])

AND Gate

In [9]:
step_func = lambda x : 1 if x >= 1.5 else 0

In [19]:
predicted = []
for i in input:
    sum = np.sum(i)
    predicted.append(step_func(sum))

In [20]:
pred = np.array(predicted)

In [23]:
for i, j, k in zip(input, output, pred):
    print(i, "--", j, "--", k)

[0 0] -- [0] -- 0
[0 1] -- [0] -- 0
[1 0] -- [0] -- 0
[1 1] -- [1] -- 1


OR Gate

In [25]:
step_func = lambda x : 1 if x >=1 else 0

In [26]:
predicted = []
for i in input:
    sum = np.sum(i)
    predicted.append(step_func(sum))

In [30]:
pred = np.array(predicted)

In [31]:
for i, j, k in zip(input, output, pred):
    print(i,"--", j,"--", k)

[0 0] -- [0] -- 0
[0 1] -- [1] -- 1
[1 0] -- [1] -- 1
[1 1] -- [1] -- 1


In [58]:
class McCulloch_Pitts:
    def __init__(self, threshold):
        self.threshold = threshold
        
    def training(self, input):
        if np.sum(i) >= self.threshold:
            return 1
        else:
            return 0

In [59]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])

In [60]:
and_gate = McCulloch_Pitts(1.5)
for i in input:
    op = and_gate.training(i)
    print("Input",i,"Output",op)

Input [0 0] Output 0
Input [0 1] Output 0
Input [1 0] Output 0
Input [1 1] Output 1


In [61]:
or_gate = McCulloch_Pitts(1)
for i in input:
    op = or_gate.training(i)
    print("Input",i,"Output",op)

Input [0 0] Output 0
Input [0 1] Output 1
Input [1 0] Output 1
Input [1 1] Output 1


In [76]:
new_inp = np.array([[0,0],[0,1],[1,0],[1,1]])
weights = np.random.rand(4)
bias = np.ones(4).reshape(-1,1)

In [77]:
weights

array([0.59985508, 0.40411576, 0.69170866, 0.5814035 ])

In [78]:
bias

array([[1.],
       [1.],
       [1.],
       [1.]])

In [79]:
step_function = lambda x : 1 if x >=30 else 0

In [80]:
learning_rate = 0.5

In [100]:
y_pred = []
for i, j in zip(input, weights):
    pred = np.sum(np.dot(i, j))
    y_pred.append(step_function(pred))

error = output.ravel() - np.array(y_pred)
error

array([0, 0, 0, 1])

In [102]:
for i in range(30):
    y_pred = []
    for i, j in zip(input, weights):
        pred = np.sum(np.dot(i, j))
        y_pred.append(step_function(pred))

    error = output.ravel() - np.array(y_pred)
    if np.sum(error)!=0:
        weights - weights *learning_rate + error
    else:
        print(weights)